# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-23 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(default='NA', max_length=50)),
                ('answer_text', models.CharField(default='NA', max_length=50)),
                ('operator', models.CharField(default='EQ', max_length=2)),
                ('date_of_assessment', models.CharField(max_length=50)),
                ('details_of_assessment', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assigned_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Assigned_question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('due_date', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_text', models.CharField(default='unknown', max_length=200)),
                ('num_of_question', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=200, null=True)),
                ('file_location', models.CharField(blank=True, max_length=1000, null=True)),
                ('upload_date', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group_member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucs.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(blank=True, max_length=10000, null=True)),
                ('unit', models.CharField(blank=True, max_length=200, null=True)),
                ('close_date', models.CharField(blank=True, max_length=200, null=True)),
                ('true_value', models.CharField(blank=True, max_length=200, null=True)),
                ('upload_date', models.CharField(blank=True, max_length=200, null=True)),
                ('question_type', models.BooleanField(default=True)),
                ('forecast', models.BooleanField(default=True)),
                ('corporate_training', models.BooleanField(default=True)),
                ('allow_assessment', models.BooleanField(default=True)),
                ('num_of_choices', models.IntegerField(default=0)),
                ('question_source', models.CharField(blank=True, max_length=1000, null=True)),
                ('question_description', models.CharField(blank=True, max_length=10000, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucs.Category')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('admin_user', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='uploader_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucs.User'),
        ),
        migrations.AddField(
            model_name='group_member',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucs.User'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='uploader_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucs.User'),
        ),
        migrations.AddField(
            model_name='assigned_question',
            name='assignment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucs.Assignment'),
        ),
        migrations.AddField(
            model_name='assigned_question',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucs.Question'),
        ),
        migrations.AddField(
            model_name='assigned_group',
            name='assignment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucs.Assignment'),
        ),
        migrations.AddField(
            model_name='assigned_group',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucs.Group'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucs.Question'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucs.User'),
        ),
    ]
