# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-07 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='operator',
            field=models.CharField(default='LE', max_length=2),
        ),
    ]
