# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-07 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ucs', '0003_assignment_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='time_of_assessment',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
